- hosts: ssfnzas911
  gather_facts: no
  tasks:
    - name: 'webhook type'
      local_action:
        module: zabbix_mediatype
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "webhook type"
        type: 4
        description: "this is a webhook"
        script: "/* some java script to implement it*/"
        timeout_param: '40s'
        parameters:
          - {'name': 'foo1', 'value': 'bar1'}
          - {'name': 'foo2', 'value': 'bar2'}
          - {'name': 'foo3', 'value': 'bar3'}
        status: 1
    - name: Create Media Type (Email)
      local_action:
        module: zabbix_mediatype
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "E-Mail"
        type: 0
        smtp_server: "localhost"
        smtp_helo: "sysfive.com"
        smtp_email: "zbx@sysfive.com"
        status: 0
        smtp_port: 25
        description: "this is an email mediatype"
    - name: Create Media Type (Script)
      local_action:
        module: zabbix_mediatype
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "Script"
        type: 1
        exec_path: "/var/lib/zabbix/alertscripts/foobar.sh"
        status: 1
        exec_params: "{ALERT.SENDTO}\n{ALERT.SUBJECT}\n{ALERT.MESSAGE}\n"
    # testing delete...
    - name: 'delete test script 0'
      local_action:
        module: zabbix_mediatype
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "test script 0"
        type: 1
        state: absent
    - name: 'SMS type'
      local_action:
        module: zabbix_mediatype
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "SMS type"
        gsm_modem: "/dev/null"
        type: 2
    - name: 'foo'
      local_action:
        module: zabbix_mediatype
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "foo"
        type: 0
        state: absent
    - name: 'another example'
      local_action:
        module: zabbix_mediatype
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "more SMS"
        type: 2
        gsm_modem: "/dev/null"
        status: 1
