- hosts: ssfnzas911
  gather_facts: no
  # fallback to python2, since no python3-seliux available
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  become: true
  tasks:
    - name: create nginx.conf for debugging/postdata
      template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root mode=0644
      tags: [ 'debug', 'postdata' ]

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      tags: [ 'debug', 'postdata' ]
