- hosts: ssfnzas911
  gather_facts: no
  tasks:
    - name: Get users via module
      local_action:
        module: zabbix_user
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        username: johndoe
        name: "John"
        surname: "Doe"
        passwd: "supersecret"
        usergroups:
          - usrgrpid: "7"
          - usrgrpid: "8"
        media:
          - mediatypeid: "1"
            sendto: "foo@example.com"
            severity: 24
            period: "1-7,00:00-24:00"
          - mediatypeid: "1"
            sendto: "alal@example.com"
            severity: 63
