- hosts: ssfnzas911
  gather_facts: no
  tasks:
    - name: Set users via module
      local_action:
        module: zabbix_user
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        username: johndoe
        name: "John"
        surname: "Doe"
        passwd: "supersecret"
        usergroups:
          - "Guests"
          - "Zabbix administrators"
        media:
          - mediatypeid: "35"
            sendto: "foo@example.com"
            severity: 24
            period: "1-7,00:00-24:00"
          - mediatypeid: "35"
            sendto: "alal@example.com"
            severity: 63
    - name: Set users via module
      local_action:
        module: zabbix_user
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        username: janedoe
        name: "Jane"
        surname: "Doe"
        passwd: "supersecret"
        usergroups:
          - "Zabbix administrators"
    - name: Delete users via module
      local_action:
        module: zabbix_user
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        username: janedoe
        name: "Jane"
        surname: "Doe"
        passwd: "supersecret"
        state: absent
    - name: Delete users via module
      local_action:
        module: zabbix_user
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        username: janedoe
        name: "Jane"
        surname: "Doe"
        passwd: "supersecret"
        state: absent
