- hosts: ssfnzas911
  gather_facts: no
  tasks:
    - name: create non ldap user group
      local_action:
        module: zabbix_usergroup
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "Admin has no LDAP"
        gui_access: 1
        # Possible values:
        # 0 - (default) use the system default authentication method;
        # 1 - use internal authentication;
        # 2 - use LDAP authentication;
        # 3 - disable access to the frontend.
    - name: you get the worst of both worlds
      local_action:
        module: zabbix_usergroup
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "tag filters AND rights"
        tag_filters:
          - {'groupid': '6', 'tag': 'q', 'value': '3' }
          - {'groupid': '4', 'tag': 'c', 'value': '4' }
          - {'groupid': '7', 'tag': 'd', 'value': 'foo' }
          - {'groupid': '2', 'tag': 'g', 'value': '0' }
          - {'groupid': '4', 'tag': 'z', 'value': 'zu' }
          - {'groupid': '9', 'tag': 'e', 'value': 'qe' }
          - {'groupid': '5', 'tag': 'x', 'value': 'io' }
          - {'groupid': '5', 'tag': 'b', 'value': 'ag' }
        rights:
          - {'id': '1', 'permission': '2'}
          - {'id': '12', 'permission': '3'}
          - {'id': '8', 'permission': '3'}
          - {'id': '4', 'permission': '2'}
          - {'id': '11', 'permission': '3'}
    - name: tag filters....
      local_action:
        module: zabbix_usergroup
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "lots of tag filters..."
        tag_filters:
          - {'groupid': '6', 'tag': 'q', 'value': '3' }
          - {'groupid': '4', 'tag': 'c', 'value': '4' }
          - {'groupid': '7', 'tag': 'd', 'value': 'foo' }
          - {'groupid': '2', 'tag': 'g', 'value': '0' }
          - {'groupid': '4', 'tag': 'z', 'value': 'zu' }
          - {'groupid': '9', 'tag': 'e', 'value': 'qe' }
          - {'groupid': '5', 'tag': 'x', 'value': 'io' }
          - {'groupid': '5', 'tag': 'a', 'value': 'ag' }
    - name: Create a usergroup
      local_action:
        module: zabbix_usergroup
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "this is a group"
        gui_access: 2
        debug_mode: 1
        users_status: 0
    - name: "Goodbye test group 123"
      local_action:
        module: zabbix_usergroup
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "test group 123"
        state: absent
    - name: "does not exist"
      local_action:
        module: zabbix_usergroup
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "i am not a group"
        state: absent
    - name: "rights..."
      local_action:
        module: zabbix_usergroup
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "group with rights"
        rights:
          - {'id': '1', 'permission': '2'}
    - name: "more rights..."
      local_action:
        module: zabbix_usergroup
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "group with more rights"
        rights:
          - {'id': '1', 'permission': '2'}
          - {'id': '12', 'permission': '3'}
          - {'id': '8', 'permission': '3'}
          - {'id': '4', 'permission': '3'}
    - name: "and tag filters...."
      local_action:
        module: zabbix_usergroup
        server_url: "{{ zabbix_apiurl }}"
        login_user: "{{ zabbix_apiuser }}"
        login_password: "{{ zabbix_apipw }}"
        name: "group with whatever tag_filters are..."
        users_status: 1
        tag_filters:
          - {'groupid': '2', 'tag': 'foo1', 'value': 'bar1'}
          - {'groupid': '2', 'tag': 'foo2', 'value': 'bar2'}
          - {'groupid': '4', 'tag': 'foo3', 'value': 'bar3'}
